package app.phueber.trigly.actions

import app.phueber.trigly.core.Action
import app.phueber.trigly.core.ActionFactory
import app.phueber.trigly.core.ActionResult
import app.phueber.trigly.core.ComponentRequirement
import app.phueber.trigly.core.NotificationController
import app.phueber.trigly.core.SharedPayloadKeys
import app.phueber.trigly.core.SpecialAccessKind
import app.phueber.trigly.core.TriggerEvent

private val NOTIFICATION_ACCESS = listOf(
    ComponentRequirement.SpecialAccess(SpecialAccessKind.NOTIFICATION_LISTENER),
)

/**
 * The notification key to act on.
 *
 * Defaults to the key of the notification that fired the rule, which is the
 * common case by a wide margin: "when my bank app notifies me, dismiss it".
 * Taking it from the payload rather than requiring config is what makes that
 * rule expressible at all — the key is generated by the posting app and cannot
 * be known in advance.
 */
internal fun resolveKey(event: TriggerEvent, configured: String?): String? =
    configured ?: event.payload[SharedPayloadKeys.NOTIFICATION_KEY]

/** Dismisses another app's notification. */
class DismissNotificationAction(
    private val controller: NotificationController,
    private val key: String?,
) : Action {

    override suspend fun execute(event: TriggerEvent): ActionResult {
        val target = resolveKey(event, key)
            ?: return ActionResult.Failure(
                "no notification key: set '${CONFIG_KEY}', or use this action on a " +
                    "rule triggered by a notification"
            )

        return controller.dismiss(target)
    }

    companion object {
        const val TYPE = "dismiss_notification"
        const val CONFIG_KEY = "key"
    }
}

class DismissNotificationActionFactory(
    private val controller: NotificationController,
) : ActionFactory {
    override val type = DismissNotificationAction.TYPE
    override val requirements = NOTIFICATION_ACCESS

    override fun create(config: Map<String, String>): Action = DismissNotificationAction(
        controller = controller,
        key = config[DismissNotificationAction.CONFIG_KEY],
    )
}

/**
 * Presses one of a notification's own buttons — "Reply", "Snooze", "Archive".
 *
 * Identified by position rather than label, because labels are localised and
 * change between app versions while position is stable for a given
 * notification. The trade-off is that a rule breaks silently if the app
 * reorders its buttons, so the action reports how many buttons actually exist
 * when the index is out of range.
 */
class TriggerNotificationButtonAction(
    private val controller: NotificationController,
    private val key: String?,
    private val buttonIndex: Int,
) : Action {

    override suspend fun execute(event: TriggerEvent): ActionResult {
        val target = resolveKey(event, key)
            ?: return ActionResult.Failure(
                "no notification key: set '${CONFIG_KEY}', or use this action on a " +
                    "rule triggered by a notification"
            )

        return controller.triggerActionButton(target, buttonIndex)
    }

    companion object {
        const val TYPE = "notification_button"
        const val CONFIG_KEY = "key"
        const val CONFIG_BUTTON_INDEX = "buttonIndex"
    }
}

class TriggerNotificationButtonActionFactory(
    private val controller: NotificationController,
) : ActionFactory {
    override val type = TriggerNotificationButtonAction.TYPE
    override val requirements = NOTIFICATION_ACCESS

    override fun create(config: Map<String, String>): Action {
        val raw = config[TriggerNotificationButtonAction.CONFIG_BUTTON_INDEX] ?: "0"
        val index = raw.toIntOrNull()
            ?: error(
                "${TriggerNotificationButtonAction.CONFIG_BUTTON_INDEX} must be a number, " +
                    "was '$raw'"
            )
        require(index >= 0) { "button index cannot be negative, was $index" }

        return TriggerNotificationButtonAction(
            controller = controller,
            key = config[TriggerNotificationButtonAction.CONFIG_KEY],
            buttonIndex = index,
        )
    }
}
