package app.phueber.trigly.actions

import app.phueber.trigly.core.Action
import app.phueber.trigly.core.ActionFactory
import app.phueber.trigly.core.ActionResult
import app.phueber.trigly.core.chooseButton
import app.phueber.trigly.core.chooseNotification
import app.phueber.trigly.core.ConfigField
import app.phueber.trigly.core.ComponentRequirement
import app.phueber.trigly.core.NotificationController
import app.phueber.trigly.core.SharedPayloadKeys
import app.phueber.trigly.core.SpecialAccessKind
import app.phueber.trigly.core.TriggerEvent

private val NOTIFICATION_ACCESS = listOf(
    ComponentRequirement.SpecialAccess(SpecialAccessKind.NOTIFICATION_LISTENER),
)

/**
 * The notification key to act on.
 *
 * Defaults to the key of the notification that fired the rule, which is the
 * common case by a wide margin: "when my bank app notifies me, dismiss it".
 * Taking it from the payload rather than requiring config is what makes that
 * rule expressible at all — the key is generated by the posting app and cannot
 * be known in advance.
 */
internal fun resolveKey(event: TriggerEvent, configured: String?): String? =
    configured ?: event.payload[SharedPayloadKeys.NOTIFICATION_KEY]

/** Dismisses another app's notification. */
class DismissNotificationAction(
    private val controller: NotificationController,
    private val key: String?,
) : Action {

    override suspend fun execute(event: TriggerEvent): ActionResult {
        val target = resolveKey(event, key)
            ?: return ActionResult.Failure(
                "no notification key: set '${CONFIG_KEY}', or use this action on a " +
                    "rule triggered by a notification"
            )

        return controller.dismiss(target)
    }

    companion object {
        const val TYPE = "dismiss_notification"
        const val CONFIG_KEY = "key"
    }
}

class DismissNotificationActionFactory(
    private val controller: NotificationController,
) : ActionFactory {
    override val type = DismissNotificationAction.TYPE

    override val displayName = "Dismiss a notification"
    override val category = ActionCategory.NOTIFICATIONS

    /**
     * No fields. The key is generated by the posting app and, as `resolveKey`
     * says, cannot be known in advance — so the text box existed to be left
     * empty. The action now always acts on the notification that fired the rule,
     * which is what every usable configuration of it meant.
     */
    override val configFields = emptyList<ConfigField>()

    override val warning: String =
        "Acts on the notification that fired the rule, so it needs a " +
            "notification trigger above it."

    override val requirements = NOTIFICATION_ACCESS

    override fun create(config: Map<String, String>): Action = DismissNotificationAction(
        controller = controller,
        key = config[DismissNotificationAction.CONFIG_KEY],
    )
}

/**
 * Presses one of a notification's own buttons — "Reply", "Snooze", "Archive".
 *
 * **The target is not always the notification that fired the rule.** With a
 * package configured it acts on the newest live notification from that app, which
 * is what makes "when I connect to the car, press play on the music notification"
 * expressible — a Bluetooth trigger and a media target. With no package it falls
 * back to the triggering notification, the commoner case.
 *
 * The button is identified by *meaning* first, then label, then the stored index;
 * see [chooseButton] for why that order. A rule keeps working through an app
 * reordering its buttons or translating them, and reports honestly when the button
 * it wanted is simply gone rather than pressing whatever is in that position now.
 */
class TriggerNotificationButtonAction(
    private val controller: NotificationController,
    private val buttonLabel: String?,
    private val semanticAction: Int?,
    private val targetPackage: String?,
    private val legacyIndex: Int?,
) : Action {

    override suspend fun execute(event: TriggerEvent): ActionResult {
        val active = controller.activeNotifications()
        if (active.isEmpty() && !controller.isConnected) {
            return ActionResult.Failure(
                "notification access is not granted, or the listener is not bound yet"
            )
        }

        val target = chooseNotification(
            active = active,
            wantedPackage = targetPackage,
            triggeringKey = event.payload[SharedPayloadKeys.NOTIFICATION_KEY],
        ) ?: return ActionResult.Failure(
            if (targetPackage != null) {
                "no notification from '$targetPackage' is showing"
            } else {
                "no notification to act on: choose an app, or use this action on a " +
                    "rule triggered by a notification"
            }
        )

        val button = chooseButton(
            buttons = target.buttons,
            wantedSemantic = semanticAction,
            wantedLabel = buttonLabel,
            storedIndex = legacyIndex,
        ) ?: return ActionResult.Failure(
            "that notification has no button matching " +
                "'${buttonLabel ?: legacyIndex ?: "anything configured"}'. " +
                "It has ${target.buttons.size}: " +
                target.buttons.joinToString { it.label ?: "?" }
        )

        // Refused rather than attempted. Firing a reply button's intent with no
        // text attached does not send a reply — it does nothing, or opens the app
        // — and reporting success for that is the failure mode this whole action
        // is trying not to have.
        if (button.takesText) {
            return ActionResult.Failure(
                "'${button.label}' is a reply box and needs text typed into it, " +
                    "which a rule cannot supply"
            )
        }

        return controller.triggerActionButton(target.key, button.index)
    }

    companion object {
        const val TYPE = "notification_button"
        const val CONFIG_BUTTON = "button"
        const val CONFIG_BUTTON_SEMANTIC = "buttonSemantic"
        const val CONFIG_PACKAGE = "package"

        /** Kept only to resolve rules saved when a position was the sole option. */
        const val CONFIG_BUTTON_INDEX = "buttonIndex"
    }
}

class TriggerNotificationButtonActionFactory(
    private val controller: NotificationController,
) : ActionFactory {
    override val type = TriggerNotificationButtonAction.TYPE

    override val displayName = "Press a notification's button"
    override val category = ActionCategory.NOTIFICATIONS

    /**
     * One field owning three keys, because they are one choice: capturing a
     * button off a live notification records what it says, what it means, and
     * whose notification it was.
     */
    override val configFields = listOf(
        ConfigField.NotificationButton(
            key = TriggerNotificationButtonAction.CONFIG_BUTTON,
            label = "Button",
            semanticKey = TriggerNotificationButtonAction.CONFIG_BUTTON_SEMANTIC,
            packageKey = TriggerNotificationButtonAction.CONFIG_PACKAGE,
            help = "Make the notification appear, then capture the button. " +
                "Leave it empty to act on the notification that fired the rule.",
        ),
    )

    override val warning: String =
        "Matched by what the button means, then by its name. A rule reports a " +
            "failure rather than pressing a different button if the one it wants " +
            "is gone."

    override val requirements = NOTIFICATION_ACCESS

    override fun create(config: Map<String, String>): Action {
        val legacy = config[TriggerNotificationButtonAction.CONFIG_BUTTON_INDEX]
        val index = legacy?.let {
            it.toIntOrNull() ?: error(
                "${TriggerNotificationButtonAction.CONFIG_BUTTON_INDEX} must be a " +
                    "number, was '$it'"
            )
        }
        require(index == null || index >= 0) { "button index cannot be negative, was $index" }

        return TriggerNotificationButtonAction(
            controller = controller,
            buttonLabel = config[TriggerNotificationButtonAction.CONFIG_BUTTON],
            semanticAction = config[TriggerNotificationButtonAction.CONFIG_BUTTON_SEMANTIC]
                ?.toIntOrNull(),
            targetPackage = config[TriggerNotificationButtonAction.CONFIG_PACKAGE]
                ?.takeIf { it.isNotBlank() },
            legacyIndex = index,
        )
    }
}
