package app.phueber.trigly.core

import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import kotlin.coroutines.AbstractCoroutineContextElement
import kotlin.coroutines.CoroutineContext

/**
 * A named string a rule can read while it runs. See `docs/variables.md`.
 *
 * A string, and only a string. Config is already `Map<String, String>` and a
 * payload is already `Map<String, String>`, so a variable that is text keeps the
 * whole feature inside shapes that exist. There is no value type, no
 * arithmetic, and no control flow, and `docs/actions.md` weighed that trade
 * before this was built.
 *
 * ### What is declared here and what is emitted elsewhere
 *
 * A trigger already fills [TriggerEvent.payload]. This declares what is in
 * there, so the editor can list it and a person can find it. Declaring is not
 * the same as emitting, in both directions:
 *
 * - A key a trigger emits and does not declare stays private business between
 *   the trigger and whoever reads the event. `SharedPayloadKeys.NOTIFICATION_KEY`
 *   is the standing example: it is opaque, generated by the posting app, and
 *   useful only to the two actions that target a notification with it. Offering
 *   it in a picker would promise a person a value they cannot read.
 * - A key declared and never emitted is a variable that is always absent. No
 *   test can catch that, because catching it means firing a real trigger, so the
 *   guard is the [key] convention below.
 *
 * **Use the trigger's own `PAYLOAD_*` constant for [key], never a literal.**
 * That ties the declaration to the emit site through the compiler, so a rename
 * moves both. It is the only half of the emit-and-declare pair a machine can
 * check, and it is the same honesty pairing [TriggerFactory.supportsCondition]
 * documents for itself.
 */
data class VariableSpec(
    /** The [TriggerEvent.payload] key this reads. */
    val key: String,
    /** Human name for the picker. */
    val label: String,
    /**
     * What sort of value this is. Display only today: the picker groups and
     * labels by it, and nothing converts on it. It exists because the first
     * thing a comparison or a format will need is the answer to this question,
     * and asking it later means revisiting every declaration.
     */
    val kind: VariableKind = VariableKind.TEXT,
    /**
     * A realistic value, shown in the picker and substituted by the editor's
     * Test button.
     *
     * Load-bearing rather than decorative. Before this existed a test run
     * carried no payload at all, so an action that read one saw nothing, and
     * `RuleEditorViewModel` said so in as many words. A sample is what lets a
     * person judge "Battery at {{trigger.level}}%" by reading it.
     */
    val sample: String,
    val help: String? = null,
    /**
     * Whether the trigger always carries this key when it fires.
     *
     * False is common and it matters. Several triggers build their payload with
     * `buildMap` and leave a key out when the platform gave them nothing: a
     * Bluetooth device with no name, an SMS with no originating address, a
     * notification with no title, an accessibility event with no text. A picker
     * that lists those beside a key that is always there promises a value the
     * event often does not carry, and the rule then fails at run time for a
     * reason the editor could have stated.
     */
    val alwaysPresent: Boolean = true,
)

/**
 * What sort of value a [VariableSpec] holds. Display only, deliberately: see
 * [VariableSpec.kind].
 */
enum class VariableKind { TEXT, NUMBER, TIMESTAMP, PACKAGE, ADDRESS, STATE }

/**
 * The namespaces a reference can name, beyond a trigger's own type string.
 *
 * Reserved words, so a trigger type may never be one of them. `VariableTest`
 * asserts that against the registry, in the same spirit as the pinned type
 * strings.
 */
object VariableScope {

    /**
     * The leaf that fired, whichever leaf that was.
     *
     * The form to offer first. A rule usually has one trigger, and
     * `{{trigger.text}}` keeps working when the person changes which trigger it
     * is. The type-qualified form exists for the other case: a rule's trigger is
     * a tree, only one leaf fires, and a leaf that did not fire has no payload
     * to read.
     */
    const val TRIGGER = "trigger"

    /** Facts about the run that no trigger knows: [EVENT_TYPE], [EVENT_TIME], [EVENT_TIMESTAMP]. */
    const val EVENT = "event"

    /** The rule that is running: [RULE_NAME], [RULE_ID]. */
    const val RULE = "rule"

    /**
     * App-scope variables, read from the store's snapshot the engine hands
     * [EventLookup]. See [EventLookup.appVariables].
     */
    const val APP = "app"

    /**
     * What an earlier action in this same run produced, whichever of them it
     * was. See [ActionOutputs] and [EventLookup.actionOutputs].
     *
     * The form to offer first, for the reason [TRIGGER] is: it keeps working
     * when the person reorders or swaps which action produced the value. The
     * type-qualified form exists for the same reason it does for a trigger
     * leaf, a rule with two producing actions of different types can say which
     * one it means, except that here the disambiguating name is an action
     * type rather than a trigger type.
     */
    const val ACTION = "action"

    /**
     * A value this run wrote and only this run can read. Gone when the run
     * ends, and never written to storage. See [RunScope].
     *
     * The scope to reach for when a value is scaffolding rather than state: a
     * total being built across three actions, a string assembled in two steps.
     * Its whole life is one firing, so nothing has to clean it up and nothing
     * can leak it into the next firing or into another rule.
     */
    const val LOCAL = "local"

    /**
     * A value that belongs to one rule, survives its runs, and is invisible to
     * every other rule.
     *
     * This is the scope [APP] was standing in for whenever a name only ever
     * mattered to one rule. A per-rule counter or cooldown had to be given a
     * globally unique name and then sat in a list shared with every other
     * rule's private bookkeeping. Keyed by rule id in storage, so two rules
     * can both keep a `count` without agreeing on anything, and a deleted rule
     * takes its values with it.
     */
    const val MINE = "mine"

    const val EVENT_TYPE = "type"
    const val EVENT_TIME = "time"
    const val EVENT_TIMESTAMP = "timestamp"
    const val RULE_NAME = "name"
    const val RULE_ID = "id"

    val reserved: Set<String> = setOf(TRIGGER, EVENT, RULE, APP, ACTION, LOCAL, MINE)

    /**
     * The variables the engine supplies for every event, whatever fired.
     *
     * Two forms of the firing time, on purpose. `{{event.time}}` is what a
     * person means by the time, and `1787900400000` is what nobody means;
     * `{{event.timestamp}}` is what a webhook wants. Neither needs a format
     * language to be useful, which is why both are here and formats are not.
     */
    val engineVariables: List<ScopedVariable> = listOf(
        ScopedVariable(
            EVENT,
            VariableSpec(
                key = EVENT_TYPE,
                label = "Trigger type",
                kind = VariableKind.TEXT,
                sample = "notification_posted",
                help = "The type of the trigger that started this run.",
            ),
        ),
        ScopedVariable(
            EVENT,
            VariableSpec(
                key = EVENT_TIME,
                label = "Time",
                kind = VariableKind.TIMESTAMP,
                sample = "07:15",
                help = "The time the trigger fired, on this device's clock.",
            ),
        ),
        ScopedVariable(
            EVENT,
            VariableSpec(
                key = EVENT_TIMESTAMP,
                label = "Time in milliseconds",
                kind = VariableKind.NUMBER,
                sample = "1787900400000",
                help = "The time the trigger fired, for a server to read.",
            ),
        ),
        ScopedVariable(
            RULE,
            VariableSpec(
                key = RULE_NAME,
                label = "Rule name",
                kind = VariableKind.TEXT,
                sample = "Car connected",
            ),
        ),
        ScopedVariable(
            RULE,
            VariableSpec(
                key = RULE_ID,
                label = "Rule id",
                kind = VariableKind.TEXT,
                sample = "8f2c1d90-0e5a-4d1b-9c33-2f6b1a7e4c58",
            ),
        ),
    )
}

/** One [VariableSpec] with the namespace it is read under. */
data class ScopedVariable(val scope: String, val spec: VariableSpec) {
    /** What a person writes to read this, with no fallback. */
    val reference: String get() = "{{$scope.${spec.key}}}"
}

/**
 * One `{{scope.name}}` in a field, with the optional fallback that follows a
 * pipe.
 *
 * [fallback] is what makes an absent value acceptable *visibly*, in the field
 * itself, rather than by a rule buried in the resolver. Without one, an absent
 * value fails the action; see [substitute].
 */
data class VariableRef(val scope: String, val name: String, val fallback: String? = null) {
    /** The reference without its fallback, for a message that names it. */
    val reference: String get() = "{{$scope.$name}}"
}

/** One piece of a parsed field value. */
sealed interface TemplateSegment {

    /** Text to copy through untouched. */
    data class Literal(val text: String) : TemplateSegment

    data class Reference(val ref: VariableRef) : TemplateSegment

    /**
     * A complete `{{...}}` whose contents name nothing.
     *
     * Kept as its own segment rather than silently treated as literal text, so
     * the editor can say which text is wrong and the resolver can refuse to run
     * on it. A person who typed `{{trigger}}` meant to read something.
     */
    data class Malformed(val raw: String, val reason: String) : TemplateSegment
}

/**
 * A field value, parsed into literal text and the references inside it.
 *
 * The grammar is one production and no more:
 *
 * ```
 * {{ <scope> . <name> [ | <fallback text> ] }}
 * ```
 *
 * An unbalanced `{{` is literal text, so nothing needs an escape character. The
 * only string that cannot be written literally is a complete, well-formed
 * reference, which nobody types by accident.
 */
data class Template(val segments: List<TemplateSegment>) {

    val references: List<VariableRef> =
        segments.filterIsInstance<TemplateSegment.Reference>().map { it.ref }

    val malformed: List<TemplateSegment.Malformed> =
        segments.filterIsInstance<TemplateSegment.Malformed>()

    /** Whether this needs resolving at all. A plain field takes the fast path. */
    val hasReferences: Boolean get() = references.isNotEmpty() || malformed.isNotEmpty()

    /**
     * Whether the whole field is exactly one reference and nothing else.
     *
     * This is what decides whether [Substitution] encoding applies. A reference
     * embedded in other text is a *value inside a structure*: a query parameter,
     * a JSON string, and it has to be escaped or it breaks the structure around
     * it. A field that is nothing but a reference *is* the value, and encoding it
     * would corrupt it: `{{app.endpoint}}` as a whole URL must not come out
     * percent-encoded.
     *
     * One rule, two behaviours, and both are what the person plainly wrote.
     *
     * [Substitution.EXPRESSION] is the one encoding this does not describe.
     * See its KDoc: an expression field is source text to evaluate, never the
     * value itself, so [substitute] does not read this flag for it.
     */
    val isSingleReference: Boolean
        get() = segments.size == 1 && segments.single() is TemplateSegment.Reference
}

/** Parses a stored field value. Never throws: bad input becomes [TemplateSegment.Malformed]. */
fun parseTemplate(raw: String): Template {
    val segments = mutableListOf<TemplateSegment>()
    val literal = StringBuilder()

    fun flush() {
        if (literal.isNotEmpty()) {
            segments += TemplateSegment.Literal(literal.toString())
            literal.setLength(0)
        }
    }

    var index = 0
    while (index < raw.length) {
        val open = raw.indexOf(OPEN, index)
        if (open < 0) {
            literal.append(raw, index, raw.length)
            break
        }
        val close = raw.indexOf(CLOSE, open + OPEN.length)
        if (close < 0) {
            // An unbalanced opener is text. See [Template].
            literal.append(raw, index, raw.length)
            break
        }
        literal.append(raw, index, open)
        flush()
        segments += segmentFor(
            body = raw.substring(open + OPEN.length, close),
            raw = raw.substring(open, close + CLOSE.length),
        )
        index = close + CLOSE.length
    }
    flush()

    return Template(segments)
}

private const val OPEN = "{{"
private const val CLOSE = "}}"
private const val FALLBACK_SEPARATOR = '|'

private fun segmentFor(body: String, raw: String): TemplateSegment {
    val separator = body.indexOf(FALLBACK_SEPARATOR)
    val namePart = (if (separator < 0) body else body.substring(0, separator)).trim()
    val fallback = if (separator < 0) null else body.substring(separator + 1).trim()

    fun malformed(reason: String) = TemplateSegment.Malformed(raw, reason)

    val dot = namePart.indexOf('.')
    if (dot < 0) return malformed("'$namePart' names no group. Write group.name, as in trigger.text.")

    val scope = namePart.substring(0, dot)
    val name = namePart.substring(dot + 1)
    if (scope.isEmpty()) return malformed("The group before the dot is empty.")
    if (name.isEmpty()) return malformed("The name after the dot is empty.")
    if (namePart.any { it.isWhitespace() }) {
        return malformed("A variable name cannot contain a space.")
    }

    return TemplateSegment.Reference(VariableRef(scope, name, fallback))
}

/** What one [VariableRef] resolved to for one run. */
sealed interface VariableValue {

    data class Present(val value: String) : VariableValue

    /**
     * Named correctly, and this run has no value for it. [reason] is shown to
     * the person, so it says *why*: the leaf did not fire, the platform did not
     * supply the key, the name is not one this rule offers.
     */
    data class Absent(val reason: String) : VariableValue
}

/**
 * Where a value comes from. Pure on purpose.
 *
 * Two implementations exist and neither can suspend: the editor reads declared
 * samples, and the engine reads a payload it already has plus a snapshot of
 * app-scope values it fetched *before* resolving. See
 * [EventLookup.appVariables] for where that snapshot is taken and why it is
 * taken once per action rather than once per event.
 */
fun interface VariableLookup {
    fun value(ref: VariableRef): VariableValue
}

/**
 * How a substituted value is escaped for the place it lands in.
 *
 * Declared on the field, not chosen by the resolver, because the same value
 * needs different treatment depending on where it goes. A notification title
 * containing a quotation mark is fine in a notification, breaks a JSON body,
 * and silently adds a query parameter in a URL if it contains an ampersand. A
 * malformed webhook that answers 400 with nothing to explain it is the quiet
 * failure this whole project is built against.
 *
 * Encoding applies to an *embedded* reference only. See
 * [Template.isSingleReference].
 *
 * There is deliberately no entry for a regular expression yet. `Pattern.quote`
 * is the whole implementation, and nothing in phase 1 can reach it: the only
 * pattern fields belong to triggers, a trigger's config is read when it is
 * built rather than per event, and a trigger cannot read a variable out of its
 * own event. It arrives with the field that needs it.
 */
enum class Substitution {

    /** This field does not accept variables. `{{...}}` in it is literal text. */
    NONE,

    /** Copy the value through. For prose: a notification, a spoken message, a toast. */
    TEXT,

    /** Percent-encode, for a value inside a URL. */
    URL,

    /** Escape for the inside of a JSON string. The quotes stay the author's. */
    JSON_STRING,

    /**
     * Render as a literal the expression language in `Expression.kt` can
     * parse: a value that reads as a number goes in bare, anything else goes
     * in as a double-quoted string with its own quotes and backslashes
     * escaped. `set_variable`'s evaluate mode is the one field that declares
     * this, only while that mode is chosen: see
     * `SetVariableActionFactory.substitutionsFor`.
     *
     * This field is never the exemption [Template.isSingleReference]
     * describes for the other encodings. A field whose whole value is one
     * reference is still, for every other [Substitution], a *value* rather
     * than a value embedded in structure, so encoding it would corrupt it:
     * `{{app.endpoint}}` as a whole URL must not come back percent-encoded.
     * An expression field is never the value itself. It is always source
     * text to run through the evaluator, even when the whole field is one
     * reference: `{{app.count}}` alone, typed as the entire expression, has
     * to become the literal `42` or `"Pixel Buds"` before it is anything the
     * evaluator can read. Skipping the encoding there would hand the
     * evaluator raw device text. That is `upper(Pixel Buds)` for the bare
     * reference case, or a bare `Pixel Buds` with nothing to quote it.
     * Neither is parseable, so it would fail every evaluate-mode field whose
     * value is not already a number. See [Template.substitute].
     */
    EXPRESSION,
    ;

    fun encode(value: String): String = when (this) {
        NONE, TEXT -> value
        URL -> percentEncode(value)
        JSON_STRING -> jsonEscape(value)
        EXPRESSION -> expressionLiteral(value)
    }
}

/**
 * A literal the expression language can read back as [value], per
 * [Substitution.EXPRESSION].
 *
 * [looksLikeExpressionNumber] is the same check `Expression.kt`'s lexer uses
 * to read a NUMBER token, so a value this inserts bare is guaranteed to parse
 * as the number it names rather than as a bare, unquoted identifier the
 * parser cannot make sense of.
 */
private fun expressionLiteral(value: String): String =
    if (looksLikeExpressionNumber(value)) value else "\"${expressionStringEscape(value)}\""

/** Escapes for the inside of this language's string literal, matching its own lexer. */
private fun expressionStringEscape(value: String): String = buildString {
    for (char in value) {
        when (char) {
            '\\' -> append("\\\\")
            '"' -> append("\\\"")
            else -> append(char)
        }
    }
}

/**
 * Percent-encodes everything outside the unreserved set of RFC 3986.
 *
 * Hand-rolled rather than `URLEncoder`, which is an HTML form encoder: it turns
 * a space into `+`, which is wrong anywhere but a form body, and leaves `*`
 * alone, which is not unreserved. Ten lines beats explaining that difference in
 * a bug report.
 */
private fun percentEncode(value: String): String = buildString {
    for (byte in value.toByteArray(Charsets.UTF_8)) {
        val char = byte.toInt().toChar()
        if (char.isLetterOrDigit() && char.code < 128 || char in "-_.~") {
            append(char)
        } else {
            append('%').append("%02X".format(byte.toInt() and 0xFF))
        }
    }
}

/** Escapes for the inside of a JSON string, without adding the quotes. */
private fun jsonEscape(value: String): String = buildString {
    for (char in value) {
        when {
            char == '"' -> append("\\\"")
            char == '\\' -> append("\\\\")
            char == '\n' -> append("\\n")
            char == '\r' -> append("\\r")
            char == '\t' -> append("\\t")
            char < ' ' -> append("\\u%04x".format(char.code))
            else -> append(char)
        }
    }
}

/** The outcome of resolving one field. */
sealed interface Substituted {

    data class Ok(val value: String) : Substituted

    /**
     * The field could not be resolved, so the action must not run. [reason]
     * names the reference and says what was wrong with it.
     */
    data class Failed(val reason: String) : Substituted
}

/**
 * This field with every reference replaced by its value.
 *
 * **An absent value fails the field.** `TriggerNode.holds` set the precedent
 * that unknown is not yes, and the same reasoning applies with more force here:
 * an empty string in a notification is cosmetic, and an empty string in a
 * webhook URL or an SMS is a wrong action taken quietly. A person who is happy
 * with empty says so in the field, with a fallback, where it can be read.
 *
 * The fallback is encoded too. It is a value the author typed, not structure,
 * and a fallback of `he said "no"` must not break the JSON around it either.
 */
fun Template.substitute(lookup: VariableLookup, encoding: Substitution): Substituted {
    // Checked before anything is resolved, and the loop below handles the same
    // case again. That is deliberate rather than dead: it decides which of two
    // failures a person is shown first. Malformed text is a typo that has to be
    // fixed whatever the data does, and a reference that resolved to nothing
    // may well resolve next time, so the typo is the more useful thing to say.
    malformed.firstOrNull()?.let {
        return Substituted.Failed("'${it.raw}' is not a variable. ${it.reason}")
    }

    // EXPRESSION is excluded here on purpose: see its KDoc and
    // Template.isSingleReference's. Every other encoding treats a field that
    // is exactly one reference as the value itself; an expression field is
    // always source text to evaluate, so it always needs the literal
    // encoding, even when nothing else is next to it.
    val whole = isSingleReference && encoding != Substitution.EXPRESSION
    val out = StringBuilder()

    for (segment in segments) {
        when (segment) {
            is TemplateSegment.Literal -> out.append(segment.text)

            is TemplateSegment.Malformed -> return Substituted.Failed(
                "'${segment.raw}' is not a variable. ${segment.reason}"
            )

            is TemplateSegment.Reference -> {
                val raw = when (val value = lookup.value(segment.ref)) {
                    is VariableValue.Present -> value.value
                    is VariableValue.Absent -> segment.ref.fallback ?: return Substituted.Failed(
                        "${segment.ref.reference} had no value. ${value.reason}"
                    )
                }
                out.append(if (whole) raw else encoding.encode(raw))
            }
        }
    }

    return Substituted.Ok(out.toString())
}

/**
 * What every earlier action in the current run has produced, for
 * [EventLookup] to resolve `{{action.*}}` and a type-qualified action
 * reference against.
 *
 * Immutable and grows one action at a time: [TriggerEngine] merges an
 * action's [ActionResult.Success.outputs] into a fresh [ActionOutputs] right
 * after that action returns, and hands the result to the next action's
 * [EventLookup]. That mirrors the reason [EventLookup.appVariables] is read
 * fresh before every action rather than once per event: a rule's actions run
 * in sequence, and a later one has to see what an earlier one just produced.
 * An action that produces nothing calls [plus] with an empty map, which is a
 * no-op, so a rule with no producing action pays nothing extra.
 *
 * A fresh, empty instance starts every event. Nothing here persists past the
 * run it was built for, so one event's outputs can never leak into the next.
 */
data class ActionOutputs(
    private val mostRecentByKey: Map<String, String> = emptyMap(),
    private val byInstance: Map<String, Map<String, String>> = emptyMap(),
) {

    /**
     * Folds in what the action at namespace [instance] produced. [outputs]
     * empty returns this unchanged, which is the fast path for the vast
     * majority of actions that declare no outputs at all.
     *
     * [instance] is a namespace from [componentInstanceNames], not a type
     * string, so two actions of one type keep their outputs apart instead of
     * the second silently replacing the first.
     */
    fun plus(instance: String, outputs: Map<String, String>): ActionOutputs {
        if (outputs.isEmpty()) return this
        return ActionOutputs(
            mostRecentByKey = mostRecentByKey + outputs,
            byInstance = byInstance + (instance to (byInstance[instance].orEmpty() + outputs)),
        )
    }

    /**
     * The most recent producer of [name], whichever action type it was. See
     * [VariableScope.ACTION].
     */
    fun value(name: String): VariableValue = mostRecentByKey[name]?.let(VariableValue::Present)
        ?: VariableValue.Absent("No action earlier in this run has produced '$name'.")

    /**
     * What the action at namespace [instance] produced for [name], or null when
     * that action has not run yet, or ran and produced nothing named [name].
     * Null rather than [VariableValue.Absent], so [EventLookup] can fall
     * through to its own message when [instance] names nothing in this rule.
     */
    fun value(instance: String, name: String): String? = byInstance[instance]?.get(name)

    companion object {
        val EMPTY = ActionOutputs()
    }
}

/**
 * Reads variables out of one event of one rule. The engine's [VariableLookup].
 *
 * A leaf that did not fire has nothing to read, and saying so is the whole
 * value of this class over a map lookup: "the Bluetooth trigger is not what
 * started this run" is actionable, and an empty string is not.
 */
class EventLookup(
    private val rule: Rule,
    private val event: TriggerEvent,
    private val zone: ZoneId = ZoneId.systemDefault(),
    /**
     * The app-scope store, as of a moment the caller chose. Defaulted to
     * empty, which is what every caller outside `TriggerEngine` gets and what
     * keeps this class usable with no store at all.
     *
     * **Read once per action, not once per event.** `TriggerEngine.ActionSlot`
     * fetches only the names an action's own templates reference, and it does
     * so immediately before that action runs, not once for the whole event
     * before the first action. A rule's actions run in sequence, and one of
     * them can be `set_variable`, writing a value a later action reads. A
     * snapshot taken once up front would show that later action the value
     * from before the write, which contradicts the one thing "a list of
     * actions" plainly means: they run in order, and a later one sees what an
     * earlier one did.
     */
    private val appVariables: Map<String, String> = emptyMap(),
    /**
     * What every earlier action in this run has produced. Defaulted to
     * [ActionOutputs.EMPTY], the same "usable with nothing wired up" default
     * [appVariables] gets. See [ActionOutputs] for why this grows across a run
     * rather than being read once.
     */
    private val actionOutputs: ActionOutputs = ActionOutputs.EMPTY,
    /**
     * The namespace of the trigger leaf that actually fired, from
     * [componentInstanceNames]. Null when the caller has no tree to number,
     * which is every caller that is not the engine.
     *
     * The engine knows this and nothing else does: `startRule` already carries
     * the fired leaf's path through the merge, because `resolveHolds` needs it.
     * Numbering the leaves turns that path into the one namespace allowed to
     * read the payload. Every other leaf namespace is refused, however well
     * configured it is, because a leaf that did not fire has no payload.
     *
     * When null the bare trigger type is treated as the fired instance, which
     * is what `{{bluetooth_connected.name}}` meant before instances existed.
     */
    private val firedTriggerInstance: String? = null,
    /**
     * `{{local.*}}`: what this firing has written so far. A snapshot taken
     * immediately before this action, the same as [appVariables] and for the
     * same reason. See [RunScope] for where the live values sit.
     */
    private val localVariables: Map<String, String> = emptyMap(),
    /**
     * `{{mine.*}}`: this rule's own persisted values, read fresh before every
     * action for the reason [appVariables] is.
     */
    private val ruleVariables: Map<String, String> = emptyMap(),
) : VariableLookup {

    override fun value(ref: VariableRef): VariableValue = when (ref.scope) {
        VariableScope.TRIGGER -> fromPayload(ref.name, event.triggerType)

        VariableScope.EVENT -> when (ref.name) {
            VariableScope.EVENT_TYPE -> VariableValue.Present(event.triggerType)
            VariableScope.EVENT_TIME -> VariableValue.Present(
                TIME_FORMAT.format(Instant.ofEpochMilli(event.firedAtMillis).atZone(zone))
            )
            VariableScope.EVENT_TIMESTAMP ->
                VariableValue.Present(event.firedAtMillis.toString())
            else -> unknown(ref)
        }

        VariableScope.RULE -> when (ref.name) {
            VariableScope.RULE_NAME -> VariableValue.Present(rule.name)
            VariableScope.RULE_ID -> VariableValue.Present(rule.id)
            else -> unknown(ref)
        }

        VariableScope.APP -> appVariables[ref.name]?.let(VariableValue::Present)
            ?: VariableValue.Absent("'${ref.name}' is not set.")

        VariableScope.LOCAL -> localVariables[ref.name]?.let(VariableValue::Present)
            ?: VariableValue.Absent(
                "'${ref.name}' has not been set in this run. A run value is gone " +
                    "when the run ends, so an action before this one has to write it."
            )

        VariableScope.MINE -> ruleVariables[ref.name]?.let(VariableValue::Present)
            ?: VariableValue.Absent("'${ref.name}' is not set for this rule.")

        VariableScope.ACTION -> actionOutputs.value(ref.name)

        // The leaf that fired, under its own namespace. Numbered by position,
        // so a rule holding two of one trigger type can say which it means.
        firedTriggerInstance ?: event.triggerType -> fromPayload(ref.name, ref.scope)

        // An action instance. It reads only what that action produced earlier
        // in this run, whether or not its namespace looks like a trigger type.
        else -> actionOutputs.value(ref.scope, ref.name)?.let(VariableValue::Present)
            ?: VariableValue.Absent(unavailableScope(ref))
    }

    /**
     * Why a namespace gave nothing, said as the different things it can mean.
     * One message covering all of them would leave the person guessing which
     * they hit, and they are fixed in different ways: pick a different trigger,
     * move the action, or correct the name.
     */
    private fun unavailableScope(ref: VariableRef): String {
        val fired = firedTriggerInstance ?: event.triggerType
        val looksLikeThisTriggerType = ref.scope == event.triggerType ||
            ref.scope.substringBeforeLast('_') == event.triggerType
        return if (looksLikeThisTriggerType) {
            "'${ref.scope}' is a trigger of the right type, but it is not the one " +
                "that fired. '$fired' fired this time, so only " +
                "{{$fired.${ref.name}}} has a value."
        } else {
            "'${ref.scope}' is not what started this rule, and no action of that " +
                "name has produced '${ref.name}' yet in this run. '$fired' " +
                "started this run."
        }
    }

    private fun fromPayload(name: String, type: String): VariableValue =
        event.payload[name]?.let(VariableValue::Present)
            ?: VariableValue.Absent("'$type' did not carry '$name' this time.")

    private fun unknown(ref: VariableRef) =
        VariableValue.Absent("Trigly has no variable named ${ref.reference}.")

    private companion object {
        val TIME_FORMAT: DateTimeFormatter = DateTimeFormatter.ofPattern("HH:mm")
    }
}

/**
 * Reads declared samples instead of a real event. What the editor previews and
 * what its Test button runs on.
 *
 * A sample for every name the rule offers, so a preview is never blank and a
 * test never fails for want of an event that has not happened. The screen has to
 * say the values are samples; this cannot say it for itself.
 */
class SampleLookup(private val available: List<ScopedVariable>) : VariableLookup {

    override fun value(ref: VariableRef): VariableValue =
        available.firstOrNull { it.scope == ref.scope && it.spec.key == ref.name }
            ?.let { VariableValue.Present(it.spec.sample) }
            ?: VariableValue.Absent("Trigly has no variable named ${ref.reference}.")
}

/**
 * The variables a rule can read, given the trigger tree it has. What the
 * editor's picker lists and what its validation checks against.
 *
 * The engine's own variables come first, because they work whatever fired.
 * What follows depends on how many leaves the tree has, and the two cases are
 * deliberately exclusive rather than additive.
 *
 * **One leaf: the short form only.** `{{trigger.title}}` reads the leaf that
 * fired, and with one leaf there is nothing else it could mean. It is the form
 * to write, because it keeps working when the person swaps which trigger the
 * rule has.
 *
 * **Two or more leaves: the instance forms only, and not the short form.**
 * With two leaves `{{trigger.title}}` cannot say *which* payload arrives, and
 * this function's contract is to offer exactly what is available at this
 * point. So each leaf is offered under its own namespace from
 * [componentInstanceNames]: `notification_posted` and `notification_posted_2`
 * for two leaves of one type, which is the whole point of numbering them.
 *
 * The consequence is real and is accepted: a rule saved with
 * `{{trigger.title}}` that later gains a second leaf holds a reference this no
 * longer offers, so save-time validation refuses it. The editor rewrites that
 * reference when the second leaf is added, which is what keeps the refusal
 * from ever reaching a person who did nothing wrong. See
 * `rewriteShortFormForNewLeaf`. The engine still *resolves* the short form,
 * so an imported rule keeps running rather than dying on an event.
 *
 * [VariableSpec.alwaysPresent] is recomputed rather than copied, and that is the
 * point of doing this here instead of in the screen. Under the short form a key
 * is always present only if the single leaf declares it so. Under an instance
 * form it is never always present once there are two leaves, because another
 * leaf may be the one that fired. The editor can then mark it, and the person
 * finds out while writing the rule rather than from a failed run.
 */
fun availableVariables(
    trigger: TriggerNode?,
    variablesOf: (String) -> List<VariableSpec>,
): List<ScopedVariable> {
    val leaves = trigger?.leaves().orEmpty()

    if (leaves.size <= 1) {
        // One leaf, so the short form is unambiguous and is the only form
        // offered. The declaration's own mark is honest here: there is no
        // other leaf that could have fired instead.
        val declared = leaves.singleOrNull()?.let { variablesOf(it.type) }.orEmpty()
        return VariableScope.engineVariables +
            declared.map { ScopedVariable(VariableScope.TRIGGER, it) }
    }

    // Two or more leaves: one namespace per leaf, numbered by position, and no
    // short form. Never always-present, because only one leaf fires per run.
    val instances = componentInstanceNames(leaves.map { it.type })
    val perInstance = leaves.mapIndexed { index, leaf ->
        variablesOf(leaf.type).map { spec ->
            ScopedVariable(instances[index], spec.copy(alwaysPresent = false))
        }
    }.flatten()

    return VariableScope.engineVariables + perInstance
}

/**
 * What is wrong with the references in [value], as sentences to show the person.
 *
 * Empty means the field resolves against *some* run. It does not promise the
 * run has a value: a key a trigger only sometimes carries is a legitimate
 * reference, and [VariableSpec.alwaysPresent] is how the editor warns about
 * that separately.
 *
 * Called at save time, which is the point. A name nobody offers is a rule that
 * fails every time it fires, and finding that out from a fault log is finding
 * out too late.
 *
 * **The three writable scopes are accepted on sight, and that is deliberate.**
 * They are the one place where checking harder would be wrong. App variables are
 * written by rules, so the rule that reads `{{app.trip_count}}` is very often
 * saved before the rule that first sets it, and refusing that save would make
 * the two rules impossible to write in either order. `{{mine.*}}` has the same
 * shape inside one rule: the action that reads a value is often written before
 * the action that sets it, and a rule is saved half-built all the time.
 *
 * `{{local.*}}` is accepted for a different and weaker reason: this function
 * *cannot* know. A run-scope name exists only because some action earlier in
 * the same run writes it, and finding that out would mean knowing which action
 * type writes variables and which of its config keys holds the name. That is
 * one component's identity in a shared file, which the plugin rule forbids for
 * the reason `Rule.appVariablesRead` gives about the same temptation. Being
 * lenient here is honest about the gap. `docs/todo.md` holds the item that
 * would close it: a declaration on the factory saying "I write a variable, and
 * its name is in this key", which would let the picker offer run-scope names
 * and let this be exact.
 *
 * Nor is there a name left to check. [variableNameProblem] asks whether a name
 * can be read back by a rule, and it asks it by round-tripping the name through
 * this same parser. A name that arrived here inside a parsed reference has
 * already answered that question by existing, so calling it again could only
 * ever agree. The check belongs where a name is *typed*, which is the writing
 * action, not where one is read.
 */
private val WRITABLE_SCOPES =
    setOf(VariableScope.APP, VariableScope.MINE, VariableScope.LOCAL)

fun variableProblems(value: String, available: List<ScopedVariable>): List<String> {
    val template = parseTemplate(value)
    val lookup = SampleLookup(available)

    val malformed = template.malformed.map { "'${it.raw}' is not a variable. ${it.reason}" }

    val unresolvable = template.references
        .filterNot { it.scope in WRITABLE_SCOPES }
        .filter { lookup.value(it) is VariableValue.Absent }
        .map { "There is no variable named ${it.reference} in this rule." }

    return malformed + unresolvable
}

/**
 * What an action can read from the actions that run before it, per
 * [ActionOutputs]. The action half of what the editor's picker lists and what
 * its validation checks against, and the reason a declared output is reachable
 * at all: [availableVariables] walks a trigger tree, so on its own it makes
 * every `{{action.*}}` reference a name nobody offers.
 *
 * [index] is the position of the action doing the reading, and only
 * [actionTypes] before it are considered. That is not a nicety. The engine
 * grows [ActionOutputs] as each action returns, so an action naming a *later*
 * action's output resolves absent on every single firing. Offering it would be
 * exactly the dead end `ConfigSchemaContractTest` refuses for a trigger that
 * never fires: pickable, saveable, and empty for ever.
 *
 * **Every producing instance gets its own namespace**, from
 * [componentInstanceNames], so two `set_variable` actions above this one are
 * `{{set_variable.value}}` and `{{set_variable_2.value}}` rather than one name
 * whose meaning depends on which ran last. The numbering is positional, and
 * the editor rewrites these references when a delete or a reorder moves an
 * action; see [rewriteInstanceReferences].
 *
 * The unnumbered [VariableScope.ACTION] form is offered as well, and means
 * "whichever action produced this most recently". It is the form to write when
 * a rule has one producer and the person does not want the reference to care
 * which action it was.
 *
 * **Nothing here is ever [VariableSpec.alwaysPresent]**, whatever the
 * declaration says. This is the opposite of [availableVariables]'s rule for a
 * single trigger leaf, and the reason is that an earlier action running is not
 * the same as it producing. It can fail before it gets that far, and a mode can
 * succeed while producing nothing: `set_variable`'s clear mode stores no value,
 * so it reports none.
 */
fun availableActionOutputs(
    actionTypes: List<String>,
    index: Int,
    variablesOf: (String) -> List<VariableSpec>,
): List<ScopedVariable> {
    val earlierCount = index.coerceIn(0, actionTypes.size)
    // Numbered across the whole rule, not just the part above this action, so
    // an action's namespace does not change depending on who is reading it.
    val instances = componentInstanceNames(actionTypes)

    val perInstance = (0 until earlierCount).flatMap { position ->
        variablesOf(actionTypes[position]).map { spec ->
            ScopedVariable(instances[position], spec.copy(alwaysPresent = false))
        }
    }
    if (perInstance.isEmpty()) return emptyList()

    val shared = perInstance
        .distinctBy { it.spec.key }
        .map { ScopedVariable(VariableScope.ACTION, it.spec) }

    return shared + perInstance
}

/**
 * The namespace each component instance answers to, for [types] in the order
 * they appear in the rule. The first instance of a type is the bare type
 * string, the second is `<type>_2`, the third `<type>_3`.
 *
 * One function, called by everything, because the numbering is a *contract*
 * between three places that must never disagree: the picker offering
 * `{{notification_posted_2.title}}`, save-time validation accepting it, and
 * the engine resolving it at run time. Two of those computing the number their
 * own way would produce a rule that saves and then reads the wrong trigger,
 * which is the failure this whole area exists to avoid.
 *
 * The first instance keeps the bare type string on purpose. It is what
 * `{{bluetooth_connected.name}}` already meant in every rule saved before
 * instances existed, so those references keep their meaning rather than
 * needing a migration.
 *
 * **The number is a position, and positions move.** Deleting the first of
 * three `notification_posted` leaves makes the old third one the second, so a
 * saved `_2` would quietly start reading a different trigger. Nothing in the
 * grammar can detect that, because the reference still resolves. The editor is
 * what closes it: see [rewriteInstanceReferences], which rewrites a rule's
 * references whenever a delete or a reorder changes this mapping. Positional
 * numbering without that rewrite is not safe.
 */
fun componentInstanceNames(types: List<String>): List<String> {
    val seen = mutableMapOf<String, Int>()
    return types.map { type ->
        val ordinal = (seen[type] ?: 0) + 1
        seen[type] = ordinal
        if (ordinal == 1) type else "${type}_$ordinal"
    }
}

/**
 * Where a `{{local.*}}` value lives: one firing of one rule, and nothing else.
 *
 * A coroutine context element rather than a store, for the reason
 * `TriggerEngine`'s run chain is one. [Action.execute] takes only a
 * [TriggerEvent], so a run-scoped write has no store to go to and no parameter
 * to arrive by. It does, however, happen on the one coroutine that is running
 * this firing, so the engine puts the map on that coroutine and `set_variable`
 * reads it back out. A field on the engine would mix two rules firing at the
 * same time into one namespace.
 *
 * Mutable, deliberately, unlike [ActionOutputs] which the engine rebuilds
 * between actions. An action writes here itself, so there is nothing for the
 * engine to rebuild it from: the write has to reach the next action without
 * the engine ever being told it happened.
 *
 * **A `run_rule` chain shares one of these.** The engine sets it once, at the
 * base of a firing, and a nested run does not replace it, so a rule can hand a
 * value to a rule it calls. That is the honest reading of "this run": the whole
 * chain is one firing, started by one event. `{{mine.*}}` is the opposite, and
 * has to be, because that scope is keyed by rule id and a called rule is a
 * different rule.
 */
class RunScope(
    /**
     * The rule this firing belongs to, so an action can write a value keyed to
     * it without being told which rule it is in.
     *
     * Carried here rather than passed to the action, for the reason the values
     * are: [Action.execute] takes only a [TriggerEvent]. A `run_rule` chain is
     * the one case where this and the shared values part company. The values
     * are shared down the chain, because the chain is one firing; this is
     * replaced for a called rule, because `{{mine.*}}` belongs to whichever
     * rule is running now and a called rule is a different rule.
     */
    val ruleId: String,
    private val values: MutableMap<String, String> = mutableMapOf(),
) : AbstractCoroutineContextElement(Key) {

    /** The same values, for a called rule that keeps them but changes owner. */
    fun forRule(otherRuleId: String): RunScope = RunScope(otherRuleId, values)

    fun snapshot(): Map<String, String> = values.toMap()

    fun set(name: String, value: String) {
        values[name] = value
    }

    fun remove(name: String) {
        values.remove(name)
    }

    companion object Key : CoroutineContext.Key<RunScope>
}
