package app.phueber.trigly.core

import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter

/**
 * A named string a rule can read while it runs. See `docs/variables.md`.
 *
 * A string, and only a string. Config is already `Map<String, String>` and a
 * payload is already `Map<String, String>`, so a variable that is text keeps the
 * whole feature inside shapes that exist. There is no value type, no
 * arithmetic, and no control flow, and `docs/actions.md` weighed that trade
 * before this was built.
 *
 * ### What is declared here and what is emitted elsewhere
 *
 * A trigger already fills [TriggerEvent.payload]. This declares what is in
 * there, so the editor can list it and a person can find it. Declaring is not
 * the same as emitting, in both directions:
 *
 * - A key a trigger emits and does not declare stays private business between
 *   the trigger and whoever reads the event. `SharedPayloadKeys.NOTIFICATION_KEY`
 *   is the standing example: it is opaque, generated by the posting app, and
 *   useful only to the two actions that target a notification with it. Offering
 *   it in a picker would promise a person a value they cannot read.
 * - A key declared and never emitted is a variable that is always absent. No
 *   test can catch that, because catching it means firing a real trigger, so the
 *   guard is the [key] convention below.
 *
 * **Use the trigger's own `PAYLOAD_*` constant for [key], never a literal.**
 * That ties the declaration to the emit site through the compiler, so a rename
 * moves both. It is the only half of the emit-and-declare pair a machine can
 * check, and it is the same honesty pairing [TriggerFactory.supportsCondition]
 * documents for itself.
 */
data class VariableSpec(
    /** The [TriggerEvent.payload] key this reads. */
    val key: String,
    /** Human name for the picker. */
    val label: String,
    /**
     * What sort of value this is. Display only today: the picker groups and
     * labels by it, and nothing converts on it. It exists because the first
     * thing a comparison or a format will need is the answer to this question,
     * and asking it later means revisiting every declaration.
     */
    val kind: VariableKind = VariableKind.TEXT,
    /**
     * A realistic value, shown in the picker and substituted by the editor's
     * Test button.
     *
     * Load-bearing rather than decorative. Before this existed a test run
     * carried no payload at all, so an action that read one saw nothing, and
     * `RuleEditorViewModel` said so in as many words. A sample is what lets a
     * person judge "Battery at {{trigger.level}}%" by reading it.
     */
    val sample: String,
    val help: String? = null,
    /**
     * Whether the trigger always carries this key when it fires.
     *
     * False is common and it matters. Several triggers build their payload with
     * `buildMap` and leave a key out when the platform gave them nothing: a
     * Bluetooth device with no name, an SMS with no originating address, a
     * notification with no title, an accessibility event with no text. A picker
     * that lists those beside a key that is always there promises a value the
     * event often does not carry, and the rule then fails at run time for a
     * reason the editor could have stated.
     */
    val alwaysPresent: Boolean = true,
)

/**
 * What sort of value a [VariableSpec] holds. Display only, deliberately: see
 * [VariableSpec.kind].
 */
enum class VariableKind { TEXT, NUMBER, TIMESTAMP, PACKAGE, ADDRESS, STATE }

/**
 * The namespaces a reference can name, beyond a trigger's own type string.
 *
 * Reserved words, so a trigger type may never be one of them. `VariableTest`
 * asserts that against the registry, in the same spirit as the pinned type
 * strings.
 */
object VariableScope {

    /**
     * The leaf that fired, whichever leaf that was.
     *
     * The form to offer first. A rule usually has one trigger, and
     * `{{trigger.text}}` keeps working when the person changes which trigger it
     * is. The type-qualified form exists for the other case: a rule's trigger is
     * a tree, only one leaf fires, and a leaf that did not fire has no payload
     * to read.
     */
    const val TRIGGER = "trigger"

    /** Facts about the run that no trigger knows: [EVENT_TYPE], [EVENT_TIME], [EVENT_TIMESTAMP]. */
    const val EVENT = "event"

    /** The rule that is running: [RULE_NAME], [RULE_ID]. */
    const val RULE = "rule"

    /**
     * App-scope variables, read from the store's snapshot the engine hands
     * [EventLookup]. See [EventLookup.appVariables].
     */
    const val APP = "app"

    const val EVENT_TYPE = "type"
    const val EVENT_TIME = "time"
    const val EVENT_TIMESTAMP = "timestamp"
    const val RULE_NAME = "name"
    const val RULE_ID = "id"

    val reserved: Set<String> = setOf(TRIGGER, EVENT, RULE, APP)

    /**
     * The variables the engine supplies for every event, whatever fired.
     *
     * Two forms of the firing time, on purpose. `{{event.time}}` is what a
     * person means by the time, and `1787900400000` is what nobody means;
     * `{{event.timestamp}}` is what a webhook wants. Neither needs a format
     * language to be useful, which is why both are here and formats are not.
     */
    val engineVariables: List<ScopedVariable> = listOf(
        ScopedVariable(
            EVENT,
            VariableSpec(
                key = EVENT_TYPE,
                label = "Trigger type",
                kind = VariableKind.TEXT,
                sample = "notification_posted",
                help = "The type of the trigger that started this run.",
            ),
        ),
        ScopedVariable(
            EVENT,
            VariableSpec(
                key = EVENT_TIME,
                label = "Time",
                kind = VariableKind.TIMESTAMP,
                sample = "07:15",
                help = "The time the trigger fired, on this device's clock.",
            ),
        ),
        ScopedVariable(
            EVENT,
            VariableSpec(
                key = EVENT_TIMESTAMP,
                label = "Time in milliseconds",
                kind = VariableKind.NUMBER,
                sample = "1787900400000",
                help = "The time the trigger fired, for a server to read.",
            ),
        ),
        ScopedVariable(
            RULE,
            VariableSpec(
                key = RULE_NAME,
                label = "Rule name",
                kind = VariableKind.TEXT,
                sample = "Car connected",
            ),
        ),
        ScopedVariable(
            RULE,
            VariableSpec(
                key = RULE_ID,
                label = "Rule id",
                kind = VariableKind.TEXT,
                sample = "8f2c1d90-0e5a-4d1b-9c33-2f6b1a7e4c58",
            ),
        ),
    )
}

/** One [VariableSpec] with the namespace it is read under. */
data class ScopedVariable(val scope: String, val spec: VariableSpec) {
    /** What a person writes to read this, with no fallback. */
    val reference: String get() = "{{$scope.${spec.key}}}"
}

/**
 * One `{{scope.name}}` in a field, with the optional fallback that follows a
 * pipe.
 *
 * [fallback] is what makes an absent value acceptable *visibly*, in the field
 * itself, rather than by a rule buried in the resolver. Without one, an absent
 * value fails the action; see [substitute].
 */
data class VariableRef(val scope: String, val name: String, val fallback: String? = null) {
    /** The reference without its fallback, for a message that names it. */
    val reference: String get() = "{{$scope.$name}}"
}

/** One piece of a parsed field value. */
sealed interface TemplateSegment {

    /** Text to copy through untouched. */
    data class Literal(val text: String) : TemplateSegment

    data class Reference(val ref: VariableRef) : TemplateSegment

    /**
     * A complete `{{...}}` whose contents name nothing.
     *
     * Kept as its own segment rather than silently treated as literal text, so
     * the editor can say which text is wrong and the resolver can refuse to run
     * on it. A person who typed `{{trigger}}` meant to read something.
     */
    data class Malformed(val raw: String, val reason: String) : TemplateSegment
}

/**
 * A field value, parsed into literal text and the references inside it.
 *
 * The grammar is one production and no more:
 *
 * ```
 * {{ <scope> . <name> [ | <fallback text> ] }}
 * ```
 *
 * An unbalanced `{{` is literal text, so nothing needs an escape character. The
 * only string that cannot be written literally is a complete, well-formed
 * reference, which nobody types by accident.
 */
data class Template(val segments: List<TemplateSegment>) {

    val references: List<VariableRef> =
        segments.filterIsInstance<TemplateSegment.Reference>().map { it.ref }

    val malformed: List<TemplateSegment.Malformed> =
        segments.filterIsInstance<TemplateSegment.Malformed>()

    /** Whether this needs resolving at all. A plain field takes the fast path. */
    val hasReferences: Boolean get() = references.isNotEmpty() || malformed.isNotEmpty()

    /**
     * Whether the whole field is exactly one reference and nothing else.
     *
     * This is what decides whether [Substitution] encoding applies. A reference
     * embedded in other text is a *value inside a structure*: a query parameter,
     * a JSON string, and it has to be escaped or it breaks the structure around
     * it. A field that is nothing but a reference *is* the value, and encoding it
     * would corrupt it: `{{app.endpoint}}` as a whole URL must not come out
     * percent-encoded.
     *
     * One rule, two behaviours, and both are what the person plainly wrote.
     */
    val isSingleReference: Boolean
        get() = segments.size == 1 && segments.single() is TemplateSegment.Reference
}

/** Parses a stored field value. Never throws: bad input becomes [TemplateSegment.Malformed]. */
fun parseTemplate(raw: String): Template {
    val segments = mutableListOf<TemplateSegment>()
    val literal = StringBuilder()

    fun flush() {
        if (literal.isNotEmpty()) {
            segments += TemplateSegment.Literal(literal.toString())
            literal.setLength(0)
        }
    }

    var index = 0
    while (index < raw.length) {
        val open = raw.indexOf(OPEN, index)
        if (open < 0) {
            literal.append(raw, index, raw.length)
            break
        }
        val close = raw.indexOf(CLOSE, open + OPEN.length)
        if (close < 0) {
            // An unbalanced opener is text. See [Template].
            literal.append(raw, index, raw.length)
            break
        }
        literal.append(raw, index, open)
        flush()
        segments += segmentFor(
            body = raw.substring(open + OPEN.length, close),
            raw = raw.substring(open, close + CLOSE.length),
        )
        index = close + CLOSE.length
    }
    flush()

    return Template(segments)
}

private const val OPEN = "{{"
private const val CLOSE = "}}"
private const val FALLBACK_SEPARATOR = '|'

private fun segmentFor(body: String, raw: String): TemplateSegment {
    val separator = body.indexOf(FALLBACK_SEPARATOR)
    val namePart = (if (separator < 0) body else body.substring(0, separator)).trim()
    val fallback = if (separator < 0) null else body.substring(separator + 1).trim()

    fun malformed(reason: String) = TemplateSegment.Malformed(raw, reason)

    val dot = namePart.indexOf('.')
    if (dot < 0) return malformed("'$namePart' names no group. Write group.name, as in trigger.text.")

    val scope = namePart.substring(0, dot)
    val name = namePart.substring(dot + 1)
    if (scope.isEmpty()) return malformed("The group before the dot is empty.")
    if (name.isEmpty()) return malformed("The name after the dot is empty.")
    if (namePart.any { it.isWhitespace() }) {
        return malformed("A variable name cannot contain a space.")
    }

    return TemplateSegment.Reference(VariableRef(scope, name, fallback))
}

/** What one [VariableRef] resolved to for one run. */
sealed interface VariableValue {

    data class Present(val value: String) : VariableValue

    /**
     * Named correctly, and this run has no value for it. [reason] is shown to
     * the person, so it says *why*: the leaf did not fire, the platform did not
     * supply the key, the name is not one this rule offers.
     */
    data class Absent(val reason: String) : VariableValue
}

/**
 * Where a value comes from. Pure on purpose.
 *
 * Two implementations exist and neither can suspend: the editor reads declared
 * samples, and the engine reads a payload it already has plus a snapshot of
 * app-scope values it fetched *before* resolving. See
 * [EventLookup.appVariables] for where that snapshot is taken and why it is
 * taken once per action rather than once per event.
 */
fun interface VariableLookup {
    fun value(ref: VariableRef): VariableValue
}

/**
 * How a substituted value is escaped for the place it lands in.
 *
 * Declared on the field, not chosen by the resolver, because the same value
 * needs different treatment depending on where it goes. A notification title
 * containing a quotation mark is fine in a notification, breaks a JSON body,
 * and silently adds a query parameter in a URL if it contains an ampersand. A
 * malformed webhook that answers 400 with nothing to explain it is the quiet
 * failure this whole project is built against.
 *
 * Encoding applies to an *embedded* reference only. See
 * [Template.isSingleReference].
 *
 * There is deliberately no entry for a regular expression yet. `Pattern.quote`
 * is the whole implementation, and nothing in phase 1 can reach it: the only
 * pattern fields belong to triggers, a trigger's config is read when it is
 * built rather than per event, and a trigger cannot read a variable out of its
 * own event. It arrives with the field that needs it.
 */
enum class Substitution {

    /** This field does not accept variables. `{{...}}` in it is literal text. */
    NONE,

    /** Copy the value through. For prose: a notification, a spoken message, a toast. */
    TEXT,

    /** Percent-encode, for a value inside a URL. */
    URL,

    /** Escape for the inside of a JSON string. The quotes stay the author's. */
    JSON_STRING,
    ;

    fun encode(value: String): String = when (this) {
        NONE, TEXT -> value
        URL -> percentEncode(value)
        JSON_STRING -> jsonEscape(value)
    }
}

/**
 * Percent-encodes everything outside the unreserved set of RFC 3986.
 *
 * Hand-rolled rather than `URLEncoder`, which is an HTML form encoder: it turns
 * a space into `+`, which is wrong anywhere but a form body, and leaves `*`
 * alone, which is not unreserved. Ten lines beats explaining that difference in
 * a bug report.
 */
private fun percentEncode(value: String): String = buildString {
    for (byte in value.toByteArray(Charsets.UTF_8)) {
        val char = byte.toInt().toChar()
        if (char.isLetterOrDigit() && char.code < 128 || char in "-_.~") {
            append(char)
        } else {
            append('%').append("%02X".format(byte.toInt() and 0xFF))
        }
    }
}

/** Escapes for the inside of a JSON string, without adding the quotes. */
private fun jsonEscape(value: String): String = buildString {
    for (char in value) {
        when {
            char == '"' -> append("\\\"")
            char == '\\' -> append("\\\\")
            char == '\n' -> append("\\n")
            char == '\r' -> append("\\r")
            char == '\t' -> append("\\t")
            char < ' ' -> append("\\u%04x".format(char.code))
            else -> append(char)
        }
    }
}

/** The outcome of resolving one field. */
sealed interface Substituted {

    data class Ok(val value: String) : Substituted

    /**
     * The field could not be resolved, so the action must not run. [reason]
     * names the reference and says what was wrong with it.
     */
    data class Failed(val reason: String) : Substituted
}

/**
 * This field with every reference replaced by its value.
 *
 * **An absent value fails the field.** `TriggerNode.holds` set the precedent
 * that unknown is not yes, and the same reasoning applies with more force here:
 * an empty string in a notification is cosmetic, and an empty string in a
 * webhook URL or an SMS is a wrong action taken quietly. A person who is happy
 * with empty says so in the field, with a fallback, where it can be read.
 *
 * The fallback is encoded too. It is a value the author typed, not structure,
 * and a fallback of `he said "no"` must not break the JSON around it either.
 */
fun Template.substitute(lookup: VariableLookup, encoding: Substitution): Substituted {
    // Checked before anything is resolved, and the loop below handles the same
    // case again. That is deliberate rather than dead: it decides which of two
    // failures a person is shown first. Malformed text is a typo that has to be
    // fixed whatever the data does, and a reference that resolved to nothing
    // may well resolve next time, so the typo is the more useful thing to say.
    malformed.firstOrNull()?.let {
        return Substituted.Failed("'${it.raw}' is not a variable. ${it.reason}")
    }

    val whole = isSingleReference
    val out = StringBuilder()

    for (segment in segments) {
        when (segment) {
            is TemplateSegment.Literal -> out.append(segment.text)

            is TemplateSegment.Malformed -> return Substituted.Failed(
                "'${segment.raw}' is not a variable. ${segment.reason}"
            )

            is TemplateSegment.Reference -> {
                val raw = when (val value = lookup.value(segment.ref)) {
                    is VariableValue.Present -> value.value
                    is VariableValue.Absent -> segment.ref.fallback ?: return Substituted.Failed(
                        "${segment.ref.reference} had no value. ${value.reason}"
                    )
                }
                out.append(if (whole) raw else encoding.encode(raw))
            }
        }
    }

    return Substituted.Ok(out.toString())
}

/**
 * Reads variables out of one event of one rule. The engine's [VariableLookup].
 *
 * A leaf that did not fire has nothing to read, and saying so is the whole
 * value of this class over a map lookup: "the Bluetooth trigger is not what
 * started this run" is actionable, and an empty string is not.
 */
class EventLookup(
    private val rule: Rule,
    private val event: TriggerEvent,
    private val zone: ZoneId = ZoneId.systemDefault(),
    /**
     * The app-scope store, as of a moment the caller chose. Defaulted to
     * empty, which is what every caller outside `TriggerEngine` gets and what
     * keeps this class usable with no store at all.
     *
     * **Read once per action, not once per event.** `TriggerEngine.ActionSlot`
     * fetches only the names an action's own templates reference, and it does
     * so immediately before that action runs, not once for the whole event
     * before the first action. A rule's actions run in sequence, and one of
     * them can be `set_variable`, writing a value a later action reads. A
     * snapshot taken once up front would show that later action the value
     * from before the write, which contradicts the one thing "a list of
     * actions" plainly means: they run in order, and a later one sees what an
     * earlier one did.
     */
    private val appVariables: Map<String, String> = emptyMap(),
) : VariableLookup {

    override fun value(ref: VariableRef): VariableValue = when (ref.scope) {
        VariableScope.TRIGGER -> fromPayload(ref.name, event.triggerType)

        VariableScope.EVENT -> when (ref.name) {
            VariableScope.EVENT_TYPE -> VariableValue.Present(event.triggerType)
            VariableScope.EVENT_TIME -> VariableValue.Present(
                TIME_FORMAT.format(Instant.ofEpochMilli(event.firedAtMillis).atZone(zone))
            )
            VariableScope.EVENT_TIMESTAMP ->
                VariableValue.Present(event.firedAtMillis.toString())
            else -> unknown(ref)
        }

        VariableScope.RULE -> when (ref.name) {
            VariableScope.RULE_NAME -> VariableValue.Present(rule.name)
            VariableScope.RULE_ID -> VariableValue.Present(rule.id)
            else -> unknown(ref)
        }

        VariableScope.APP -> appVariables[ref.name]?.let(VariableValue::Present)
            ?: VariableValue.Absent("'${ref.name}' is not set.")

        // A trigger type. It reads only when it is the leaf that fired.
        event.triggerType -> fromPayload(ref.name, event.triggerType)

        else -> VariableValue.Absent(
            "'${ref.scope}' is not what started this rule. '${event.triggerType}' did."
        )
    }

    private fun fromPayload(name: String, type: String): VariableValue =
        event.payload[name]?.let(VariableValue::Present)
            ?: VariableValue.Absent("'$type' did not carry '$name' this time.")

    private fun unknown(ref: VariableRef) =
        VariableValue.Absent("Trigly has no variable named ${ref.reference}.")

    private companion object {
        val TIME_FORMAT: DateTimeFormatter = DateTimeFormatter.ofPattern("HH:mm")
    }
}

/**
 * Reads declared samples instead of a real event. What the editor previews and
 * what its Test button runs on.
 *
 * A sample for every name the rule offers, so a preview is never blank and a
 * test never fails for want of an event that has not happened. The screen has to
 * say the values are samples; this cannot say it for itself.
 */
class SampleLookup(private val available: List<ScopedVariable>) : VariableLookup {

    override fun value(ref: VariableRef): VariableValue =
        available.firstOrNull { it.scope == ref.scope && it.spec.key == ref.name }
            ?.let { VariableValue.Present(it.spec.sample) }
            ?: VariableValue.Absent("Trigly has no variable named ${ref.reference}.")
}

/**
 * The variables a rule can read, given the trigger tree it has. What the
 * editor's picker lists and what its validation checks against.
 *
 * The engine's own variables come first, because they work whatever fired. Then
 * the union of every leaf's declarations under [VariableScope.TRIGGER], which is
 * the form to reach for: one name that keeps working when the person changes
 * which trigger the rule has.
 *
 * The type-qualified form is offered **only when the tree has more than one
 * leaf**, because that is the only time it says anything the short form does
 * not. Listing both for a one-trigger rule would double the picker to no
 * purpose.
 *
 * [VariableSpec.alwaysPresent] is recomputed rather than copied, and that is the
 * point of doing this here instead of in the screen. A key is always present
 * under [VariableScope.TRIGGER] only if *every* leaf that could fire declares
 * it, and a key read from one named leaf of several is never always present,
 * because another leaf may be what fired. The editor can then mark it, and the
 * person finds out while writing the rule rather than from a failed run.
 */
fun availableVariables(
    trigger: TriggerNode?,
    variablesOf: (String) -> List<VariableSpec>,
): List<ScopedVariable> {
    val leaves = trigger?.leaves().orEmpty()
    val types = leaves.map { it.type }.distinct()
    val declarations = types.associateWith(variablesOf)

    val shared = declarations.values.flatten().distinctBy { it.key }.map { spec ->
        val everyLeafHasIt = declarations.values.all { specs -> specs.any { it.key == spec.key } }
        ScopedVariable(
            VariableScope.TRIGGER,
            spec.copy(alwaysPresent = spec.alwaysPresent && everyLeafHasIt),
        )
    }

    val qualified = if (types.size < 2) {
        emptyList()
    } else {
        types.flatMap { type ->
            declarations.getValue(type).map { ScopedVariable(type, it.copy(alwaysPresent = false)) }
        }
    }

    return VariableScope.engineVariables + shared + qualified
}

/**
 * What is wrong with the references in [value], as sentences to show the person.
 *
 * Empty means the field resolves against *some* run. It does not promise the
 * run has a value: a key a trigger only sometimes carries is a legitimate
 * reference, and [VariableSpec.alwaysPresent] is how the editor warns about
 * that separately.
 *
 * Called at save time, which is the point. A name nobody offers is a rule that
 * fails every time it fires, and finding that out from a fault log is finding
 * out too late.
 *
 * **An app-scope reference is accepted on sight, and that is deliberate.** It is
 * the one place where checking harder would be wrong. App variables are written
 * by rules, so the rule that reads `{{app.trip_count}}` is very often saved
 * before the rule that first sets it, and refusing that save would make the two
 * rules impossible to write in either order.
 *
 * Nor is there a name left to check. [variableNameProblem] asks whether a name
 * can be read back by a rule, and it asks it by round-tripping the name through
 * this same parser. A name that arrived here inside a parsed reference has
 * already answered that question by existing, so calling it again could only
 * ever agree. The check belongs where a name is *typed*, which is the writing
 * action, not where one is read.
 */
fun variableProblems(value: String, available: List<ScopedVariable>): List<String> {
    val template = parseTemplate(value)
    val lookup = SampleLookup(available)

    val malformed = template.malformed.map { "'${it.raw}' is not a variable. ${it.reason}" }

    val unresolvable = template.references
        .filterNot { it.scope == VariableScope.APP }
        .filter { lookup.value(it) is VariableValue.Absent }
        .map { "There is no variable named ${it.reference} in this rule." }

    return malformed + unresolvable
}
